language: c
sudo: required
dist: trusty
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OS_SPECIFIC_ARGS="--with-openssl=/usr/local/opt/openssl"; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpam-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y automake; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export OS_SPECIFIC_ARGS=""; fi
script:
    - ./bootstrap
    - ./configure --with-pam --prefix=/usr $OS_SPECIFIC_ARGS
    - make
    - make check
