name: Duo Unix CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  nix_ci:
    name: Duo Unix - test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        cc: [gcc, clang]

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install -y autoconf libtool libpam-dev libssl-dev automake python3 python3-pip cppcheck

      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build
        env:
          CC: ${{ matrix.cc }}
        run: ./bootstrap && ./configure --with-pam --prefix=/usr && make

      - name: Install test dependencies
        run: pip3 install -r test_requirements.in

      - name: Run tests
        run: sudo make distcheck

      - name: Static analysis
        run: cppcheck --quiet --force -i tests --suppressions-list=.false_positive.txt --error-exitcode=1 .

  fips_ci:
    name: Duo Unix - FIPS runtime test (Rocky 9)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run FIPS test suite
        run: ./tests/fips/run_fips_test.sh
